version: '3.1'
services:
  spring:
    image: omericin/pu-service:v1
    volumes:
      - spring:/var/lib/spring
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATA_MONGODB_HOST=mongoservice
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=phoneselling
  mongoservice:
    image: mongo
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    expose:
      - '27017'
    environment:
      - MONGO_INITDB_DATABASE=phoneselling
    restart: always
  app:
    image: omericin/pu-app:v2
    volumes:
      - app:/var/lib/app
    ports:
      - "80:3000"
volumes:
  spring:
    external: true
  mongo_data:
    external: true
  mongo_config:
    external: true
  app:
    external: true